[package]
name = "line-density"
version = "0.2.0"
authors = ["Dominik Moritz <domoritz@gmail.com>"]

[dependencies]
imageproc = "0.22"
image = "0.23.14"
rand = "0.4.2"
palette = "*"
rayon = "*"
csv = "1"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"